package com.example;

import java.nio.file.Files;
import java.nio.file.Path;

public class App {

    public static void main(String[] args) throws Exception {

        String html = """
                <!DOCTYPE html>
                <html>
                <head>
                    <title>Maven Project</title>
                </head>
                <body>
                    <h1>Hello Spurthi!</h1>
                    <p>This HTML file was generated by a Java Maven project.</p>
                </body>
                </html>
                """;

        Files.writeString(Path.of("target/index.html"), html);

        System.out.println("HTML file created: target/index.html");
    }
}
