name: Java CI/CD Pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-test-sonarqube:
    name: CI/CD Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # SonarQube needs the complete Git history
          fetch-depth: 0

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build Java application
        run: mvn clean compile

      - name: Run unit tests
        run: mvn clean test

      - name: SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.8.0.7211:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=SpurthiHiremath_Java-CICD-with-SonarQube-Docker-and-AWS -Dsonar.organization=spurthihiremath -Dsonar.qualitygate.wait=true

      #Build the Image and name it 
      - name: Build Docker image
        run: docker build --tag java-cicd-app:latest .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@FULL_40_CHARACTER_SHA # v6.2.4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        run: |
          docker tag java-cicd-app:latest \
          ${{ steps.login-ecr.outputs.registry }}/java-cicd-app:latest
      
      - name: Push Docker image to ECR
        run: |
          docker push \
          ${{ steps.login-ecr.outputs.registry }}/java-cicd-app:latest
                  
